name: victoria_form
description: Um app feito para ajudar profissionais da saÃºde sobre tratamento de feridas.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^3.0.5
  sqflite: any
  path: any
  path_provider: any
  win32: ^4.1.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.0.0

flutter_native_splash:
  color: "#2196f3"


  image: "assets/images/logo.png"
  android: true
  ios: true
  android_gravity: center
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true
 
  assets:
      - assets/images/
